# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dozap_second/Main.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Main(genpy.Message):
  _md5sum = "bf323843762cfb3e8a894aa82e16c9f6"
  _type = "dozap_second/Main"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 motor_right
float64 motor_left
int32 rotation_a_right
int32 rotation_a_left
int32 rotation_b_right
int32 rotation_b_left
"""
  __slots__ = ['motor_right','motor_left','rotation_a_right','rotation_a_left','rotation_b_right','rotation_b_left']
  _slot_types = ['float64','float64','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_right,motor_left,rotation_a_right,rotation_a_left,rotation_b_right,rotation_b_left

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Main, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motor_right is None:
        self.motor_right = 0.
      if self.motor_left is None:
        self.motor_left = 0.
      if self.rotation_a_right is None:
        self.rotation_a_right = 0
      if self.rotation_a_left is None:
        self.rotation_a_left = 0
      if self.rotation_b_right is None:
        self.rotation_b_right = 0
      if self.rotation_b_left is None:
        self.rotation_b_left = 0
    else:
      self.motor_right = 0.
      self.motor_left = 0.
      self.rotation_a_right = 0
      self.rotation_a_left = 0
      self.rotation_b_right = 0
      self.rotation_b_left = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d4i().pack(_x.motor_right, _x.motor_left, _x.rotation_a_right, _x.rotation_a_left, _x.rotation_b_right, _x.rotation_b_left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.motor_right, _x.motor_left, _x.rotation_a_right, _x.rotation_a_left, _x.rotation_b_right, _x.rotation_b_left,) = _get_struct_2d4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d4i().pack(_x.motor_right, _x.motor_left, _x.rotation_a_right, _x.rotation_a_left, _x.rotation_b_right, _x.rotation_b_left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.motor_right, _x.motor_left, _x.rotation_a_right, _x.rotation_a_left, _x.rotation_b_right, _x.rotation_b_left,) = _get_struct_2d4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d4i = None
def _get_struct_2d4i():
    global _struct_2d4i
    if _struct_2d4i is None:
        _struct_2d4i = struct.Struct("<2d4i")
    return _struct_2d4i
